schibsted/account-sdk-android

common/src/main/java/com/schibsted/account/common/util/Util.kt
core/src/main/java/com/schibsted/account/engine/controller/Controller.kt
core/src/main/java/com/schibsted/account/engine/controller/LoginController.kt
core/src/main/java/com/schibsted/account/engine/controller/PasswordlessController.kt
core/src/main/java/com/schibsted/account/engine/controller/SignUpController.kt
core/src/main/java/com/schibsted/account/engine/step/StepNoPwIdentify.kt

When using a default class loader reading a Parcel object fails.
How to reproduce : 
1- Take any samsung device (of course)
2- launch a passwordless flow
3- go to the verification screen
4 - trigger onPause()/onResume() by clicking on the task manager button
Hurra, app will crash onResume when trying to read the parcel.

Add classloader to Parcel.readStack to avoid using the default one

---

ui/src/main/res/drawable/schacc_rounded_container.xml
ui/src/main/res/layout-h350dp-land/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout-land/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/values/colors.xml
ui/src/main/res/values/dimens.xml
ui/src/main/res/values/styles.xml

New identification UI, the new teaser text isn't included, because there's another ticket for it in progress and assigned to @Nexcius . I didn't want to redo what you might have already done :)
See the following attachement

Change identification screen UI

---

example/src/main/java/com/schibsted/account/example/MainActivity.java
ui/src/main/java/com/schibsted/account/ui/UiUtil.kt
ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt

Fixes #43 
I do know that this method is deprecated but we can't use the new one. The new one gives us a context to set in `attachBaseContext` unfortunately when this method is called it's too early to create/get the `UIConfiguration`. (I tried it with the following function)
```
@JvmStatic
fun getContext(context: Context, locale: Locale): ContextWrapper {
val resources = context.resources
var newContext = context
val conf = resources.configuration
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
conf.setLocale(locale)
newContext = context.createConfigurationContext(conf)
} else {
conf.locale = locale
resources.updateConfiguration(conf, resources.displayMetrics)
}
return ContextWrapper(newContext)
}
```

Change behavior to set the language of the application dependending on the uiConfiguration

---

ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/ui/BaseFragment.kt
ui/src/main/java/com/schibsted/account/ui/ui/FlowFragment.kt
ui/src/main/res/layout-h350dp-land/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout-h350dp-land/schacc_verification_fragment_layout.xml
ui/src/main/res/layout-land/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout-land/schacc_verification_fragment_layout.xml
ui/src/main/res/layout/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout/schacc_verification_fragment_layout.xml

Don't show keyboard when a new screen is displayed, and close it as soon as the action is performed if the provided input is valid (if not we don't show the continue button either the loading hint, it seems like the app is frozen)

Fix keyboard behavior

---

core/README.md
core/src/main/java/com/schibsted/account/persistence/UserPersistence.kt
core/src/main/java/com/schibsted/account/session/User.kt
core/src/test/java/com/schibsted/account/session/UserPersistenceTest.kt
example/src/main/java/com/schibsted/account/example/MainActivity.java

Fixes #83 
**Upgrade notes**
- `UserPersistence` is no longer available and its functionality can now be found as static functions on the `User` object. 
-  The deprecated functions for synchronously resuming sessions are now removed to adhere to the GDPR requirements of checking terms when resuming a session. You can resume sessions by providing a callback to the replacement functions.

Move functions for session handling to the User class

---

ui/README.md
ui/src/main/res/layout/schacc_mobile_activity_layout.xml
ui/src/main/res/values/colors.xml
ui/src/main/res/values/public.xml

Some clients need to have a different background colour for the schibsted account UI and the rest fo their app

Add option to change background color

---

example/src/main/java/com/schibsted/account/example/MainActivity.java
smartlock/README.md
ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/smartlock/SmartlockMode.kt

This enables the users to store credentials even after they cancel the first request to choose credentials.
Fixes #236

Add failed mode to SmartLock

---

core/src/main/java/com/schibsted/account/persistence/UserPersistence.kt
core/src/test/java/com/schibsted/account/session/UserPersistenceTest.kt

Now we don't rely on `SimpleDateFormat.getDateTimeInstance()` which rely on `Locale.getDefault(...)`
but we use a static Locale instead.
Indeed get the `Locale` dynamically could result in the crash referenced in the issue if the application allows the user to switch language (or if the user changes his system language).
Let's say I first open the application in Swedish -> date will be saved like `14 juli 2018 10:18:54`
But, you open your app again and switch language (because it's a new feature for example and you're more comfortable in English than in Swedish), `SimpleDateFormat.getDateTimeInstance()` will try to resolve the `Date` using the `Locale.En` and it's gonna fail because `Jun` is expected not `Juli`
Fixes #301

Fix issue where parsing of a date would fail

---

example/src/main/res/values/strings.xml
ui/README.md
ui/src/main/java/com/schibsted/account/ui/RequiredConfiguration.kt

Fixes #306 
Now we don't automatically put `://` to build the redirect URI but we take what's given by the client.
Because `://` was something static in the code whatever we could do to fix the issue would result in a change from the client.
I have chosen the easiest solution for us and the client by just asking the client to add whether `://` or `:/` to their host. Of course, I was first thinking of "why split this value? let's just ask the client to give us the full self-service redirect URI". Unfortunately, we can't do that because we need the scheme to be added in the *static* AndroidManifest, so we can't resolve the scheme from the full self-service URI and inject it in the `android:scheme` field. I also thought of doing `android:scheme="*"` and do a comparison between the link we …

Fix issue where redirect_uri was not correctly built

---

core/src/main/java/com/schibsted/account/model/Product.kt
core/src/main/java/com/schibsted/account/network/response/SubscriptionsResponse.kt
core/src/main/java/com/schibsted/account/network/service/BaseNetworkService.java
core/src/main/java/com/schibsted/account/network/service/user/UserContract.kt
core/src/main/java/com/schibsted/account/network/service/user/UserService.kt
core/src/main/java/com/schibsted/account/session/Profile.kt
core/src/main/java/com/schibsted/account/util/SubscriptionDeserializer.kt
example/src/main/java/com/schibsted/account/example/MainActivity.java

Fixes #272
I wrapped the list of Subscription into SubscriptionResponse because registering a TypeAdapter of Type TypeToken<List<Subscription>> wasn't working. It might be related to google/gson#1274.
Also, I created a custom deserializer because the payload we receive contains objects with a dynamic name ( the object's name correspond to the subscription id...) so Gson can't automatically parse objects.
e.g.
```
"data": {
"169252": {
"subscriptionId": "169252",
...
},
"169253": {
"subscriptionId": "169253",
...
}
}
```

Add subscription endpoint

---

example/src/main/java/com/schibsted/account/example/MainActivity.java
ui/src/main/java/com/schibsted/account/ui/login/flow/password/PasswordActivity.kt
ui/src/main/java/com/schibsted/account/ui/login/flow/passwordless/PasswordlessActivity.kt
ui/src/main/java/com/schibsted/account/ui/navigation/Navigation.kt

See #310 , this PR solved the related bug but had a side effect of re-evaluating the contract twice in some cases. e.g. : When we first navigate to the identification screen.
This PR fixes this side effect.

Fix issue where contract could be evaluated twice

---

ui/src/main/java/com/schibsted/account/ui/Event.kt
ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/login/LoginActivityViewModel.kt
ui/src/main/java/com/schibsted/account/ui/login/flow/password/PasswordActivity.kt

* Use Events Wrapper in order to have catch event only once with live data
* Do not initialize login controller when not needed.
Before this commit - 
* on device rotation user was redirected to the first screen because the ClientResult was emitted again (which cause a navigation to the first screen as intended).
* LoginController was created no matter what, and then the signup flow wasn't working (because handled by the login controller implementation, that means when you were trying to create an account under the hood the app was trying to log you in, and then you got an error saying "Sorry bro, credentials of yours are wrong".

Fix issue with behavior on rotation

---

core/src/main/java/com/schibsted/account/util/SubscriptionDeserializer.kt

Fixes #334 
When the user has no subscription the `data` field returned by spid isn't a `JsonObject` but an empty `JsonArray`

Fix issue where subscription endoint was crashing

---

example/src/main/AndroidManifest.xml
example/src/main/java/com/schibsted/account/example/MainActivity.java
ui/README.md
ui/src/main/java/com/schibsted/account/ui/AccountUi.kt
ui/src/main/java/com/schibsted/account/ui/InternalUiConfiguration.kt
ui/src/main/java/com/schibsted/account/ui/OptionalConfiguration.kt
ui/src/main/java/com/schibsted/account/ui/SignUpMode.kt
ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/ui/FlowFragment.kt
ui/src/test/java/com/schibsted/account/ui/UiConfigTest.kt
ui/src/test/java/com/schibsted/account/ui/login/LoginActivityViewModelTest.kt

Fixes #329 
***What was the problem***
The locale was always retrieved from the manifest even if overridden programmatically. That was due to the call of `OptionalConfiguration.fromManifest` instead of `OptionalConfiguration.revolve`. The last method would apply the configuration correctly but unfortunately we can call it when we need it: We need it in `attachBaseContext` but this `resolve`  method needs an `Application` object which is not created yet.
***What are the changes***
*  The `Application` object is not required any longer to resolve the optional configurations
*  All optional configurations are now defined in one place cf. `AccountUi`
*  The sdk first tries to resolve the locale from the manifest and then tries to resolve it from the runtime conf

Do not rely on the App object to get the ui conf

---

core/src/main/java/com/schibsted/account/network/service/user/UserContract.kt
core/src/main/java/com/schibsted/account/network/service/user/UserService.kt
core/src/main/java/com/schibsted/account/session/User.kt

The endpoint currently does nothing and will be deprecated.

Don't call /api/2/logout endpoint on user logout.

---

core/src/main/java/com/schibsted/account/network/AuthInterceptor.kt

This lets consumers of the SDK to create interceptor on their own OkHttpClient instance instead of relying on `user.bind()` method.
Manual PR just for Travis sake
Original in #387.

Expose Auth Interceptor outside

---

core/src/main/java/com/schibsted/account/persistence/EncryptionKeyProvider.kt

Use a start date in the past for the encryption key to avoid timezone issue with huawei p20.
See this [thread](https://github.com/iamMehedi/Secured-Preference-Store/issues/15) for more details.
This should fix https://github.com/schibsted/account-sdk-android/issues/388

Fix for Retreiving stored user credentials fails 100% time on Huawei P20 device (see #388)

---

core/src/main/java/com/schibsted/account/network/service/user/UserService.kt
core/src/main/java/com/schibsted/account/persistence/EncryptionKeyProvider.kt

According to https://techdocs.login.schibsted.com the endpoints [api/2/user/{userId}](https://techdocs.login.schibsted.com/endpoints/GET/user/%7BuserId%7D/) and [api/2/user/{userId}/product/{productId}](https://techdocs.login.schibsted.com/endpoints/GET/user/%7BuserId%7D/product/%7BproductId%7D/) should have a Bearer access token. We currently don't have that prefix set, which cause the first requests to fail, and subsequently refresh the token before finally succeeding.

Bug fix: Add a bearer prefix to the Authorization header

---

CHANGELOG.md

- Bug fix: Add a bearer prefix to the Authorization header (#394)
- Fix for Retreiving stored user credentials fails 100% time on Huawei P20 device (#392)

RELEASE <1.7.2>

---

core/src/main/java/com/schibsted/account/ClientConfiguration.kt
core/src/main/java/com/schibsted/account/network/ServiceHolder.kt

Without updating them, there is no possible way to change the environment in the runtime.
Supersedes #395 (for Travis sake).

Added resetting of services to  ClientConfiguration set method.

---

ui/src/main/java/com/schibsted/account/ui/login/screen/password/PasswordFragment.kt
ui/src/main/res/layout-land/schacc_password_fragment_layout.xml
ui/src/main/res/layout/schacc_password_fragment_layout.xml

According to current appcompat libraries setup. Tested on API 19 and 28.
*Supersedes #398.*

Fix pre-lollipop vector drawables crash

---

ui/src/main/res/layout/schacc_phone_widget.xml

1. Using passwordless SMS login (`AccountUi.FlowType.PASSWORDLESS_SMS`), click the phone number prefix input field.
1. Verify the next button is shown as below and that clicking it moves the cursor the phone number field.

Make the phone prefix input field show 'next' option in the keyboard.

---

ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/login/LoginActivityViewModel.kt
ui/src/main/java/com/schibsted/account/ui/login/LoginActivityViewModelFactory.kt
ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/EmailIdentificationFragment.kt
ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/MobileIdentificationFragment.kt
ui/src/test/java/com/schibsted/account/ui/login/LoginActivityViewModelTest.kt

If there are no stored credentials, ensure the selected account identifier is prefilled.
1. Add at least one Google accounts to the device (Settings->Accounts->Add account->Google)
1. [Enable SmartLock in the example app](https://github.com/schibsted/account-sdk-android/blob/a9fb48dd847647aaa2bdacfa83edf9f96e9ce8f6/example/src/main/java/com/schibsted/account/example/MainActivity.java#L115).
1. Run the example app and press login.
1. Verify you're prompted for which account to continue with by SmartLock and select an account.
1. Verify the selected account identifier is pre-filled as the email address.

Fix 393: Prefill identifier from SmartLock when no stored credentials.

---

smartlock/README.md
ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/smartlock/SmartlockTask.kt
ui/src/test/java/com/schibsted/account/ui/smartlock/SmartlockTaskTest.kt

To avoid unnecessarily requiring the login activity to be restarted if
SmartLock failed or was cancelled.
See #405.

Ignore SmartLock failure

---

common/src/main/java/com/schibsted/account/common/smartlock/SmartLockCallback.kt
ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/smartlock/SmartlockReceiver.kt

By marking SmartLock as done resolving when no value was retrieved, the
login flow is able to continue instead of hopelessly waiting for
SmartLock to finish (which it already has).
1. See #414 (requires account added to the device).

Fix #414: Resolve SmartLock flow when it's cancelled.

---

core/src/main/java/com/schibsted/account/AccountService.kt
core/src/main/java/com/schibsted/account/ClientConfiguration.kt
core/src/main/java/com/schibsted/account/model/error/NetworkError.kt
core/src/main/java/com/schibsted/account/network/AuthInterceptor.kt
core/src/main/java/com/schibsted/account/network/NetworkCallback.kt
core/src/main/java/com/schibsted/account/persistence/EncryptionKeyProvider.kt
core/src/main/java/com/schibsted/account/persistence/PersistenceEncryption.kt
core/src/main/java/com/schibsted/account/persistence/SessionStorageDelegate.kt
core/src/main/java/com/schibsted/account/persistence/UserPersistenceReceiver.kt
core/src/main/java/com/schibsted/account/persistence/UserPersistenceService.kt
core/src/main/java/com/schibsted/account/util/DateUtils.kt
core/src/main/java/com/schibsted/account/util/DeepLink.kt
core/src/main/java/com/schibsted/account/util/DeepLinkHandler.kt
smartlock/src/main/java/com/schibsted/account/smartlock/SmartlockController.kt
ui/src/main/java/com/schibsted/account/ui/RequiredConfiguration.kt
ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
ui/src/main/java/com/schibsted/account/ui/login/LoginActivityViewModel.kt
ui/src/main/java/com/schibsted/account/ui/login/flow/password/LoginContractImpl.kt
ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/EmailIdentificationFragment.kt
ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/MobileIdentificationFragment.kt
ui/src/main/java/com/schibsted/account/ui/login/screen/onesteplogin/OneStepLoginFragment.kt
ui/src/main/java/com/schibsted/account/ui/navigation/Navigation.kt

`SomeClass::class.java.simpleName` should not be used when code might be proguarded. Proguard renames classes, making logs gibberish.
PS: I see some files are shown with large diffs. No clue why. This whole PR contains only one actual change - replacing `::class.java.simpleName` with literal strings.

Log tags must be hardcoded.

---

buildSrc/src/main/java/SharedConfigurationPlugin.kt
common/build.gradle.kts
core/build.gradle.kts
smartlock/build.gradle.kts
ui/build.gradle.kts

For some reason IDEA doesn't resolve runCatching and a few other Kotlin functions. If I configure Kotlin in each individual project, they are resolved fine :(
This behavior is specific to Linux. I tested in other OS, like Windows - it is just fine.

Configure Kotlin in each related project

---

core/src/androidTest/java/com/schibsted/account/persistence/EncryptionKeyProviderTest.kt
core/src/main/java/com/schibsted/account/persistence/EncryptionKeyProvider.kt
core/src/main/java/com/schibsted/account/persistence/SessionStorageDelegate.kt

Just like we did for 1.11.2 but simpler.

Force RSA key refresh on upgrade to 1.12

---

buildSrc/src/main/java/SharedConfigurationPlugin.kt

Mockito-Kotlin 3.3.1 requires compatibility with Java 8 features. It is only relevant to instrumented tests which I forgot to run, of course.

Enable compatibility with Java 8 features.

---

core/src/main/java/com/schibsted/account/network/AuthInterceptor.kt

The access token is already explicitly defined in the API call methods,
so it should be overwritten and not duplicated.
Otherwise it might cause requests to be rejected by
servers which strictly adhere to the HTTP spec (which prohibits multiple
Authorization headers).

Always overwrite HTTP Authorization header in AuthInterceptor.

---

.travis.yml
release.sh

Since Travis doesn't make encrypted data available for PRs from forks,
this change should enable the tests to still run for such PRs.
The deploy step is also restricted to only the main repo.

Move decryption of deploy_key to deploy step on Travis.

---

buildSrc/src/main/java/Constants.kt
example/src/main/java/com/schibsted/account/example/MainActivity.java
ui/build.gradle.kts
ui/src/main/res/layout/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout/schacc_mobile_activity_layout.xml
ui/src/main/res/layout/schacc_password_fragment_layout.xml

Hello!
We are a bit on a bleeding-edge when it comes to the AndroidX/Jetpack libraries. Recently, we upgraded the fragment library from 1.3.0-alpha06 to 1.3.0-rc02. Unfortunately, this new version is making account-sdk-android crash. We get `NestedScrollView` must have only one child when we click "Continue" after typing in our email. I found a solution that uses `androidx.fragment.app.FragmentContainerView`. I also had to update the fragment library from 1.1.0 to 1.2.0 to make it visible, but at least it isn't alpha or rc. :slightly_smiling_face:

NestedScrollView must have only one child fix

---

ui/src/main/res/layout-land/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout-land/schacc_one_step_login_fragment_layout.xml
ui/src/main/res/layout/schacc_abstract_identification_fragment_layout.xml
ui/src/main/res/layout/schacc_one_step_login_fragment_layout.xml

When client logo (on the left) is bigger (and can be up to 150dp) than Schibsted logo  - Schibsted logo (on right) gets misaligned - glued to the top.
BEFORE:
When this PR is merged it will be nicely centered.
AFTER:

Center sch logo with client logo

---

core/src/main/java/com/schibsted/account/session/User.kt

When the refresh token is invalid (expired, user has logged out, etc), 400 Bad Request with `"error": "invalid_grant"` is returned as response. So we should treat that as a logout.

Treat 'invalid_grant' token response as logout signal.
