schibsted/account-sdk-android

- ui/src/main/java/com/schibsted/account/ui/UiConfiguration.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/LoginScreen.kt
- ui/src/main/res/menu/schacc_menu.xml
As discussed with Ali, Karmela and Jonas
> Change UIs to have the visibility of the close button configurable

- core/src/main/java/com/schibsted/account/util/ConfigurationUtils.kt
This allows for us to have comments in the configuration files
> Add # to filtering of configuration file

- README.md
- build.gradle
- ui/build.gradle
> Change location of deeplink parameters definition

- ui/README.md
- ui/src/main/java/com/schibsted/account/ui/UiUtil.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/res/layout/schacc_mobile_activity_layout.xml
- ui/src/main/res/values/colors.xml
- ui/src/main/res/values/public.xml
> Add possibility to customize toolbar colors

- core/src/main/java/com/schibsted/account/util/DeepLinkHandler.kt
> Fix issue where user was not logged in after a successful deeplink signup redirection

- example/src/main/java/com/schibsted/account/example/MainActivity.java
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
> Fix issue where smartlock was running despite the configuration was set to disabled

- core/src/main/java/com/schibsted/account/network/InfoInterceptor.kt
> Add SDK type and version header to InfoInterceptor

- gradle/wrapper/gradle-wrapper.properties
- ui/src/androidTest/java/com/schibsted/account/ui/login/screen/identification/EmailIdentificationFragmentTest.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/EmailIdentificationFragment.java
- ui/src/main/res/values-fi/strings.xml
- ui/src/main/res/values-nb/strings.xml
- ui/src/main/res/values-sv/strings.xml
- ui/src/main/res/values/strings.xml
Updated some english copies and their translations. Now uses Schibsted account instead of SPiD
> Change translations to match last design copies

- core/src/main/java/com/schibsted/account/network/ServiceHolder.kt
> Fix issue where interceptor was not cleared on logout

- common/src/main/java/com/schibsted/account/common/tracking/UiTracking.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/AbstractIdentificationFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/password/PasswordFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/verification/VerificationFragment.java
- ui/src/main/java/com/schibsted/account/ui/navigation/Navigation.kt
> Add tracking of keepMeLoggedIn and teaser

- ui/src/main/res/layout/schacc_required_fields_layout.xml
- ui/src/main/res/values-fi/strings.xml
- ui/src/main/res/values-nb/strings.xml
- ui/src/main/res/values-sv/strings.xml
- ui/src/main/res/values/strings.xml
> Update required fields screen description to be GDPR compliant

- core/src/main/java/com/schibsted/account/persistence/EncryptionKeyProvider.kt
> Fix issue where KeyStore was not loaded successfully

- core/src/main/java/com/schibsted/account/engine/controller/SignUpController.kt
- core/src/main/java/com/schibsted/account/engine/step/StepSignUpDone.kt
> Fix issue where network call was done on screen rotation

- ui/src/main/res/values-fi/strings.xml
- ui/src/main/res/values-nb/strings.xml
- ui/src/main/res/values-sv/strings.xml
- ui/src/main/res/values/strings.xml
> Update translations to for redesign

- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
> Fix issue where toolbar was updated before the UI was launched

- core/src/main/java/com/schibsted/account/network/service/authentication/OAuthService.kt
- core/src/main/java/com/schibsted/account/session/User.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
> Fix issue where signup was failing due to scopes

- ui/src/main/java/com/schibsted/account/ui/ui/WebFragment.java
- ui/src/main/res/layout/schacc_web_fragment_layout.xml
> Fix issue where webview wasn't scrollable

- ui/src/main/java/com/schibsted/account/ui/AccountUi.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/FragmentProvider.kt
- ui/src/main/java/com/schibsted/account/ui/login/flow/passwordless/PasswordlessActivity.kt
> Fix issue where login with phone number couldn't be started

- README.md
- deploy_docs.sh
- example/src/main/java/com/schibsted/account/example/MainActivity.java
- smartlock/README.md
- smartlock/src/main/java/com/schibsted/account/smartlock/SmartlockReceiver.kt
- ui/README.md
> No longer auto login after a user logs out

- ui/src/main/java/com/schibsted/account/ui/AccountUi.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/FragmentProvider.kt
> Rename passwordless phone to sms

- core/src/main/java/com/schibsted/account/network/AuthInterceptor.kt
> Fix issue where token is not cleared from the icpt

- ui/src/main/java/com/schibsted/account/ui/AccountUi.kt
> Add builder to AccountUi.Params

- core/src/main/java/com/schibsted/account/util/DeepLinkHandler.kt
> Allow for all deep link formats

- core/src/main/java/com/schibsted/account/session/User.kt
> Ensure sessions are only bound once

- core/src/test/java/com/schibsted/account/engine/controller/LoginControllerTest.kt
- example/src/main/AndroidManifest.xml
- ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/EmailIdentificationFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/information/RequiredFieldsFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/password/PasswordFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/term/TermsFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/term/TermsPresenter.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/verification/VerificationFragment.kt
- ui/src/main/java/com/schibsted/account/ui/ui/component/BirthdayInputView.kt
- ui/src/main/java/com/schibsted/account/ui/ui/component/CheckBoxView.java
- ui/src/main/java/com/schibsted/account/ui/ui/component/CodeInputView.java
- ui/src/main/java/com/schibsted/account/ui/ui/component/InputFieldView.java
- ui/src/main/java/com/schibsted/account/ui/ui/component/PasswordView.kt
- ui/src/main/java/com/schibsted/account/ui/ui/component/PhoneInputView.java
- ui/src/main/res/layout-land/schacc_password_fragment_layout.xml
- ui/src/main/res/layout-land/schacc_required_fields_layout.xml
- ui/src/main/res/layout-land/schacc_verification_fragment_layout.xml
- ui/src/main/res/layout/schacc_inbox_fragment_layout.xml
- ui/src/main/res/layout/schacc_include_accessibility_fix.xml
- ui/src/main/res/layout/schacc_password_fragment_layout.xml
- ui/src/main/res/layout/schacc_required_fields_layout.xml
- ui/src/main/res/layout/schacc_terms_fragment_layout.xml
- ui/src/main/res/layout/schacc_verification_fragment_layout.xml
- ui/src/main/res/values-fi/strings.xml
- ui/src/main/res/values-nb/strings.xml
- ui/src/main/res/values-sv/strings.xml
- ui/src/main/res/values/strings.xml
> Add accessibility labels for the UIs

- core/src/main/java/com/schibsted/account/network/service/authentication/OAuthService.kt
- core/src/main/java/com/schibsted/account/session/User.kt
- example/build.gradle
- example/src/main/res/values/strings.xml
Fixes #246, fixes #244, fixes #241
> Fix issue where aotomatic login did not work

- ui/src/main/java/com/schibsted/account/ui/navigation/Navigation.kt
> Fix crash when user exited during network load

- ui/src/main/java/com/schibsted/account/ui/login/screen/password/PasswordFragment.kt
- ui/src/main/res/layout/schacc_password_fragment_layout.xml
> Remove age disclaimer in case of login

- core/src/main/java/com/schibsted/account/model/error/ClientError.kt
- core/src/main/java/com/schibsted/account/model/error/NetworkError.kt
- example/src/main/java/com/schibsted/account/example/MainActivity.java
- smartlock/README.md
- ui/README.md
- ui/src/main/java/com/schibsted/account/ui/AccountUi.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/smartlock/SmartlockImpl.kt
> Give error back to the client when flow fails

- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/flow/passwordless/PasswordlessActivity.kt
> Fix issue where passwordless flow wasn't launched

- example/src/main/java/com/schibsted/account/example/MainActivity.java
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/LoadClientInfoTask.kt
- ui/src/main/java/com/schibsted/account/ui/navigation/Navigation.kt
FIxes #277 
That's a quick fix, BaseLoginActivity will be refactored after 1.0
> Fix issue where loading dialog was causing a crash

- core/src/main/java/com/schibsted/account/AccountService.kt
- core/src/main/java/com/schibsted/account/persistence/StorageDelegate.kt
- core/src/main/java/com/schibsted/account/persistence/UserPersistence.kt
- core/src/main/java/com/schibsted/account/session/User.kt
- core/src/test/java/com/schibsted/account/engine/controller/LoginControllerTest.kt
- core/src/test/java/com/schibsted/account/persistence/StorageDelegateTest.kt
- core/src/test/java/com/schibsted/account/session/UserPersistenceTest.kt
> Add cache for agreement status check on resume

- ui/src/main/java/com/schibsted/account/ui/login/flow/password/PasswordActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/flow/passwordless/PasswordlessActivity.kt
- ui/src/main/java/com/schibsted/account/ui/navigation/Navigation.kt
> Fix issue where presenters were not initialized after a back navigation

- core/src/main/java/com/schibsted/account/network/InfoInterceptor.kt
> Add extra info to InfoInterceptor

- ui/README.md
- ui/src/main/java/com/schibsted/account/ui/AccountUi.kt
- ui/src/main/java/com/schibsted/account/ui/InternalUiConfiguration.kt
- ui/src/main/java/com/schibsted/account/ui/OptionalConfiguration.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/password/PasswordFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/verification/VerificationFragment.kt
- ui/src/main/res/values/public.xml
- ui/src/main/res/values/strings.xml
> Add a configuration option for the remember me feature

- ui/src/main/java/com/schibsted/account/ui/AccountUi.kt
Commit of the shame 😓 
It's still possible to provide it via the constructor so it does not break the prod.
> Fix issue where a builder method was missing

- common/common-rules.pro
- core/core-rules.pro
- extract-release-aar.sh
- ui/ui-rules.pro
> Add proguard rules

- core/src/main/java/com/schibsted/account/AccountService.kt
- core/src/main/java/com/schibsted/account/engine/controller/LoginController.kt
- core/src/main/java/com/schibsted/account/engine/controller/PasswordlessController.kt
- core/src/main/java/com/schibsted/account/model/error/ClientError.kt
- core/src/main/java/com/schibsted/account/model/error/NetworkError.kt
- core/src/main/java/com/schibsted/account/network/response/DeviceFingerprint.kt
- core/src/main/java/com/schibsted/account/network/service/user/UserContract.kt
- core/src/main/java/com/schibsted/account/network/service/user/UserService.kt
- core/src/main/java/com/schibsted/account/session/Device.kt
- core/src/main/java/com/schibsted/account/session/User.kt
Create a device fingerprint after each successful login.
> Create a device fingerprint after each login

- core/src/main/java/com/schibsted/account/network/InfoInterceptor.kt
- core/src/main/java/com/schibsted/account/network/ServiceHolder.kt
- core/src/main/java/com/schibsted/account/session/User.kt
To [avoid boolean flag](https://martinfowler.com/bliki/FlagArgument.html).
> Move internal request interceptor to its own class.

- core/src/main/java/com/schibsted/account/session/User.kt
Supersedes #402 to make the CI happy.
> Added missing callback invocation on success.

- ui/src/main/java/com/schibsted/account/ui/KeyboardController.kt
- ui/src/main/java/com/schibsted/account/ui/login/BaseLoginActivity.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/EmailIdentificationFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/identification/ui/MobileIdentificationFragment.kt
- ui/src/main/java/com/schibsted/account/ui/login/screen/password/PasswordFragment.kt
- ui/src/main/java/com/schibsted/account/ui/ui/component/PhoneInputView.kt
Supersedes #406 just for Travis sake.
> Focus on the input field and pop up keyboard when opening activity

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- smartlock/build.gradle
- ui/src/main/java/com/schibsted/account/ui/navigation/Navigation.kt
- ui/src/main/java/com/schibsted/account/ui/ui/component/CodeInputView.kt
- ui/src/main/java/com/schibsted/account/ui/ui/component/CustomEditText.kt
Upgrade:
* Target and compile sdks 27 -> 28.
* BuildTools 27.0.3 -> 29.0.0
> Upgrade platform

- common/build.gradle.kts
- common/src/androidTest/java/com/schibsted/account/common/util/UtilConnectedTest.kt
- common/src/main/java/com/schibsted/account/common/lib/ObservableField.kt
- common/src/main/java/com/schibsted/account/common/util/Util.kt
- common/src/test/java/com/schibsted/account/common/lib/ObservableFieldTest.kt
- common/src/test/java/com/schibsted/account/common/util/UtilTest.kt
ObservableField.Single behaves really weird :)
It looks like it is by design but I suspect this kind of design can be a source of bugs.
> Fix tests in common

- core/src/main/java/com/schibsted/account/ClientConfiguration.kt
Honestly, I think `ClientConfiguration` should be merged with `utils.ConfigurationUtils`.
> Minor fixes to ClientConfiguration.

- buildSrc/src/main/java/PomHelpers.kt
Publication's artifact ID is set by each project separately, and it is not equal to project's name (for example, `common`'s name is "common" but artifactId is "account-sdk-android-common").
When generating POM with dependencies, we need to use artifactId instead of project's name.
> Use publication's artifactId for POM generation of ProjectDependency.

- common/build.gradle.kts
- core/build.gradle.kts
- ui/build.gradle.kts
No need to have them here now when we have dependencies up to date
> Remove exclusions from build.gradle files

- buildSrc/src/main/java/Constants.kt
- buildSrc/src/main/java/SharedConfigurationPlugin.kt
- core/build.gradle.kts
- core/src/main/java/com/schibsted/account/model/error/NetworkError.kt
- core/src/main/java/com/schibsted/account/network/AuthInterceptor.kt
- core/src/main/java/com/schibsted/account/network/NetworkCallback.kt
- core/src/test/java/com/schibsted/account/model/error/NetworkErrorTest.kt
- core/src/test/java/com/schibsted/account/network/AuthInterceptorTest.kt
- core/src/test/java/com/schibsted/account/test/MockedCall.kt
- core/src/test/java/com/schibsted/account/test/MockedResponses.kt
- example/build.gradle.kts
For compatibility with e.g. latest Firebase Crashlytics.
> Upgrade OkHttp dependency
